name: Rust Cross Compile for Raspberry Pi 5 (ARM64) and Windows (x86_64)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        component: rustfmt

    - name: Install cross
      run: cargo install cross

    - name: Build for ARM64 (Raspberry Pi 5)
      run: cross build --target aarch64-unknown-linux-gnu --release

    - name: Upload artifact for Raspberry Pi
      uses: actions/upload-artifact@v3
      with:
        name: pi-build
        path: target/aarch64-unknown-linux-gnu/release/rat_race

    - name: Build for Windows (x86_64)
      run: cross build --target x86_64-pc-windows-gnu --release

    - name: Upload artifact for Windows
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: target/x86_64-pc-windows-gnu/release/rat_race

